[package]
name = "hubcaps"
version = "0.2.8"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Github"
documentation = "https://softprops.github.io/hubcaps"
homepage = "https://github.com/softprops/hubcaps"
repository = "https://github.com/softprops/hubcaps"
keywords = ["hyper", "github"]
license = "MIT"
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_derive"]

[dev-dependencies]
env_logger = "0.3"

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
log = "0.3"
hyper = "0.9"
url = "1.2"
serde = "0.8"
serde_json = "0.8"
serde_derive = { version = "0.8", optional = true }
serializable_enum = "0.3"
