[package]
name = "hubcaps"
version = "0.2.2"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Github"
documentation = "https://softprops.github.io/hubcaps"
homepage = "https://github.com/softprops/hubcaps"
repository = "https://github.com/softprops/hubcaps"
keywords = ["hyper", "github"]
license = "MIT"
build = "build.rs"

[dev-dependencies]
env_logger="0.3"

[build-dependencies]
serde_codegen = "0.7"
syntex = "0.37"

[dependencies]
log = "0.3"
hyper = "0.9"
url = "1.0"
serde = "0.7"
serde_json = "0.7"
serializable_enum = "0.3"
